default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost       # Conexão via TCP/IP
  port: 5434            # Porta customizada (5434)
  username: felipe # Ex: felipe, postgres, etc.
  password: 123   # Se houver senha
  pool: 5

development:
  <<: *default
  database: simulate_pit_stop_api_development

test:
  <<: *default
  database: simulate_pit_stop_api_test

production:
  <<: *default
  database: simulate_pit_stop_api_production
  username: simulate_pit_stop_api
  password: <%= ENV["SIMULATE_PIT_STOP_API_DATABASE_PASSWORD"] %>
