default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  username: <%= ENV.fetch("DB_USERNAME", "felipe") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "simulate_pit_stop_api_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "simulate_pit_stop_api_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "simulate_pit_stop_api_production") %>
  username: <%= ENV.fetch("DB_USERNAME", "felipe") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
